# Site Configuration
title: "ericstrs"
url: "http://localhost"
port: 8080
description: "My personal website where I share my thoughts and experiences on technology and life."
syntax_highlighting:
  dark_mode:
    theme: "gruvbox"

# Navigation Menu
nav:
  - name: "blog"
    url: "/blogs"
  - name: "notes"
    url: "/notes"
  - name: "about"
    url: "/about"

social:
  - name: "X"
    url: "https://twitter.com/ericstrs"
  - name: "GitHub"
    url: "https://github.com/ericstrs"
